# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Jun 18 15:33:15 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_mainWindow(object):
    def setupUi(self, mainWindow):
        mainWindow.setObjectName(_fromUtf8("mainWindow"))
        mainWindow.resize(1023, 713)
        mainWindow.setMinimumSize(QtCore.QSize(1023, 713))
        mainWindow.setMaximumSize(QtCore.QSize(1023, 713))
        self.centralWidget = QtGui.QWidget(mainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.groupBox_5 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_5.setGeometry(QtCore.QRect(0, 190, 251, 281))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label = QtGui.QLabel(self.groupBox_5)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_9.addWidget(self.label, 0, 0, 1, 1)
        self.AppliedVoltage = QtGui.QLCDNumber(self.groupBox_5)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.AppliedVoltage.setFont(font)
        self.AppliedVoltage.setAutoFillBackground(True)
        self.AppliedVoltage.setMidLineWidth(0)
        self.AppliedVoltage.setSmallDecimalPoint(False)
        self.AppliedVoltage.setDigitCount(5)
        self.AppliedVoltage.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.AppliedVoltage.setProperty("value", 0.0)
        self.AppliedVoltage.setProperty("intValue", 0)
        self.AppliedVoltage.setObjectName(_fromUtf8("AppliedVoltage"))
        self.gridLayout_9.addWidget(self.AppliedVoltage, 0, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.groupBox_5)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Rounded)
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.VoltageChooser = QtGui.QDoubleSpinBox(self.tab)
        self.VoltageChooser.setGeometry(QtCore.QRect(10, 50, 121, 31))
        self.VoltageChooser.setDecimals(3)
        self.VoltageChooser.setMinimum(-1.0)
        self.VoltageChooser.setMaximum(1.0)
        self.VoltageChooser.setSingleStep(0.1)
        self.VoltageChooser.setObjectName(_fromUtf8("VoltageChooser"))
        self.ZeroVolt = QtGui.QPushButton(self.tab)
        self.ZeroVolt.setGeometry(QtCore.QRect(20, 10, 161, 23))
        self.ZeroVolt.setObjectName(_fromUtf8("ZeroVolt"))
        self.gridLayoutWidget = QtGui.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 90, 201, 83))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.p100 = QtGui.QPushButton(self.gridLayoutWidget)
        self.p100.setObjectName(_fromUtf8("p100"))
        self.gridLayout.addWidget(self.p100, 2, 0, 1, 1)
        self.p10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.p10.setObjectName(_fromUtf8("p10"))
        self.gridLayout.addWidget(self.p10, 0, 0, 1, 1)
        self.n10 = QtGui.QPushButton(self.gridLayoutWidget)
        self.n10.setObjectName(_fromUtf8("n10"))
        self.gridLayout.addWidget(self.n10, 0, 1, 1, 1)
        self.n100 = QtGui.QPushButton(self.gridLayoutWidget)
        self.n100.setObjectName(_fromUtf8("n100"))
        self.gridLayout.addWidget(self.n100, 2, 1, 1, 1)
        self.p50 = QtGui.QPushButton(self.gridLayoutWidget)
        self.p50.setObjectName(_fromUtf8("p50"))
        self.gridLayout.addWidget(self.p50, 1, 0, 1, 1)
        self.n50 = QtGui.QPushButton(self.gridLayoutWidget)
        self.n50.setObjectName(_fromUtf8("n50"))
        self.gridLayout.addWidget(self.n50, 1, 1, 1, 1)
        self.negateBias = QtGui.QPushButton(self.tab)
        self.negateBias.setGeometry(QtCore.QRect(160, 52, 51, 31))
        self.negateBias.setObjectName(_fromUtf8("negateBias"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.tab_2)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 10, 221, 171))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.mv200 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv200.setObjectName(_fromUtf8("mv200"))
        self.gridLayout_2.addWidget(self.mv200, 1, 0, 1, 1)
        self.mv500 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv500.setObjectName(_fromUtf8("mv500"))
        self.gridLayout_2.addWidget(self.mv500, 4, 0, 1, 1)
        self.mv400 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv400.setObjectName(_fromUtf8("mv400"))
        self.gridLayout_2.addWidget(self.mv400, 3, 0, 1, 1)
        self.mv100 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv100.setObjectName(_fromUtf8("mv100"))
        self.gridLayout_2.addWidget(self.mv100, 0, 0, 1, 1)
        self.mv300 = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv300.setObjectName(_fromUtf8("mv300"))
        self.gridLayout_2.addWidget(self.mv300, 2, 0, 1, 1)
        self.mv200n = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv200n.setObjectName(_fromUtf8("mv200n"))
        self.gridLayout_2.addWidget(self.mv200n, 1, 1, 1, 1)
        self.mv100n = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv100n.setObjectName(_fromUtf8("mv100n"))
        self.gridLayout_2.addWidget(self.mv100n, 0, 1, 1, 1)
        self.mv300n = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv300n.setObjectName(_fromUtf8("mv300n"))
        self.gridLayout_2.addWidget(self.mv300n, 2, 1, 1, 1)
        self.mv400n = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv400n.setObjectName(_fromUtf8("mv400n"))
        self.gridLayout_2.addWidget(self.mv400n, 3, 1, 1, 1)
        self.mv500n = QtGui.QPushButton(self.gridLayoutWidget_2)
        self.mv500n.setObjectName(_fromUtf8("mv500n"))
        self.gridLayout_2.addWidget(self.mv500n, 4, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.MakeIV = QtGui.QPushButton(self.tab_3)
        self.MakeIV.setGeometry(QtCore.QRect(20, 160, 181, 23))
        self.MakeIV.setObjectName(_fromUtf8("MakeIV"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.tab_3)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(10, 30, 201, 101))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_3 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_3.addWidget(self.label_3, 1, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 0, 0, 1, 1)
        self.label_5 = QtGui.QLabel(self.gridLayoutWidget_3)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 2, 0, 1, 1)
        self.IVBounds = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.IVBounds.setDecimals(3)
        self.IVBounds.setMaximum(1.0)
        self.IVBounds.setSingleStep(0.1)
        self.IVBounds.setObjectName(_fromUtf8("IVBounds"))
        self.gridLayout_3.addWidget(self.IVBounds, 0, 1, 1, 1)
        self.IVStep = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.IVStep.setDecimals(3)
        self.IVStep.setMaximum(1.0)
        self.IVStep.setSingleStep(0.05)
        self.IVStep.setObjectName(_fromUtf8("IVStep"))
        self.gridLayout_3.addWidget(self.IVStep, 1, 1, 1, 1)
        self.IVDwell = QtGui.QDoubleSpinBox(self.gridLayoutWidget_3)
        self.IVDwell.setDecimals(3)
        self.IVDwell.setMaximum(100.0)
        self.IVDwell.setObjectName(_fromUtf8("IVDwell"))
        self.gridLayout_3.addWidget(self.IVDwell, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabWidget, 1, 0, 1, 2)
        self.groupBox_6 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_6.setGeometry(QtCore.QRect(10, 480, 241, 171))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.ZeroVoltage = QtGui.QPushButton(self.groupBox_6)
        self.ZeroVoltage.setObjectName(_fromUtf8("ZeroVoltage"))
        self.gridLayout_4.addWidget(self.ZeroVoltage, 0, 0, 1, 1)
        self.zerovoltagevlaue = QtGui.QDoubleSpinBox(self.groupBox_6)
        self.zerovoltagevlaue.setDecimals(5)
        self.zerovoltagevlaue.setMinimum(-1.0)
        self.zerovoltagevlaue.setMaximum(1.0)
        self.zerovoltagevlaue.setSingleStep(0.001)
        self.zerovoltagevlaue.setObjectName(_fromUtf8("zerovoltagevlaue"))
        self.gridLayout_4.addWidget(self.zerovoltagevlaue, 0, 1, 1, 1)
        self.ZeroCurrent = QtGui.QPushButton(self.groupBox_6)
        self.ZeroCurrent.setObjectName(_fromUtf8("ZeroCurrent"))
        self.gridLayout_4.addWidget(self.ZeroCurrent, 1, 0, 1, 1)
        self.ZeroCurrentValue = QtGui.QLabel(self.groupBox_6)
        self.ZeroCurrentValue.setObjectName(_fromUtf8("ZeroCurrentValue"))
        self.gridLayout_4.addWidget(self.ZeroCurrentValue, 1, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_4, 0, 0, 1, 2)
        self.ReadData = QtGui.QLabel(self.groupBox_6)
        self.ReadData.setFrameShape(QtGui.QFrame.Box)
        self.ReadData.setText(_fromUtf8(""))
        self.ReadData.setObjectName(_fromUtf8("ReadData"))
        self.gridLayout_10.addWidget(self.ReadData, 1, 0, 1, 1)
        self.ReadData2 = QtGui.QLabel(self.groupBox_6)
        self.ReadData2.setFrameShape(QtGui.QFrame.Box)
        self.ReadData2.setText(_fromUtf8(""))
        self.ReadData2.setObjectName(_fromUtf8("ReadData2"))
        self.gridLayout_10.addWidget(self.ReadData2, 1, 1, 1, 1)
        self.groupBox_7 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_7.setGeometry(QtCore.QRect(0, 0, 251, 181))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.InputChooser = QtGui.QComboBox(self.groupBox_7)
        self.InputChooser.setGeometry(QtCore.QRect(10, 24, 73, 20))
        self.InputChooser.setObjectName(_fromUtf8("InputChooser"))
        self.InputChooser.addItem(_fromUtf8(""))
        self.InputChooser.addItem(_fromUtf8(""))
        self.InputChooser.addItem(_fromUtf8(""))
        self.InputChooser.addItem(_fromUtf8(""))
        self.Reconnect = QtGui.QPushButton(self.groupBox_7)
        self.Reconnect.setGeometry(QtCore.QRect(136, 23, 105, 23))
        self.Reconnect.setObjectName(_fromUtf8("Reconnect"))
        self.tabWidget_2 = QtGui.QTabWidget(self.groupBox_7)
        self.tabWidget_2.setGeometry(QtCore.QRect(10, 52, 231, 119))
        self.tabWidget_2.setObjectName(_fromUtf8("tabWidget_2"))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.verticalLayoutWidget = QtGui.QWidget(self.tab_4)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 211, 81))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.ExperimentName = QtGui.QLineEdit(self.verticalLayoutWidget)
        self.ExperimentName.setInputMask(_fromUtf8(""))
        self.ExperimentName.setObjectName(_fromUtf8("ExperimentName"))
        self.verticalLayout.addWidget(self.ExperimentName)
        self.SaveData = QtGui.QCheckBox(self.verticalLayoutWidget)
        self.SaveData.setObjectName(_fromUtf8("SaveData"))
        self.verticalLayout.addWidget(self.SaveData)
        self.WrittenBlocks = QtGui.QLabel(self.verticalLayoutWidget)
        self.WrittenBlocks.setObjectName(_fromUtf8("WrittenBlocks"))
        self.verticalLayout.addWidget(self.WrittenBlocks)
        self.tabWidget_2.addTab(self.tab_4, _fromUtf8(""))
        self.tab_5 = QtGui.QWidget()
        self.tab_5.setObjectName(_fromUtf8("tab_5"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.tab_5)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 211, 81))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.SetDataFolder = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.SetDataFolder.setObjectName(_fromUtf8("SetDataFolder"))
        self.verticalLayout_2.addWidget(self.SetDataFolder)
        self.DataFolder = QtGui.QTextBrowser(self.verticalLayoutWidget_2)
        self.DataFolder.setObjectName(_fromUtf8("DataFolder"))
        self.verticalLayout_2.addWidget(self.DataFolder)
        self.tabWidget_2.addTab(self.tab_5, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 340, 137, 171))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.LowPassValue = QtGui.QSpinBox(self.groupBox_2)
        self.LowPassValue.setMaximum(2000)
        self.LowPassValue.setSingleStep(50)
        self.LowPassValue.setProperty("value", 250)
        self.LowPassValue.setObjectName(_fromUtf8("LowPassValue"))
        self.gridLayout_7.addWidget(self.LowPassValue, 4, 0, 1, 1)
        self.LowPass = QtGui.QCheckBox(self.groupBox_2)
        self.LowPass.setObjectName(_fromUtf8("LowPass"))
        self.gridLayout_7.addWidget(self.LowPass, 5, 0, 1, 1)
        self.DisplayDownSamplingRate = QtGui.QSpinBox(self.groupBox_2)
        self.DisplayDownSamplingRate.setMinimum(1)
        self.DisplayDownSamplingRate.setMaximum(10000)
        self.DisplayDownSamplingRate.setObjectName(_fromUtf8("DisplayDownSamplingRate"))
        self.gridLayout_7.addWidget(self.DisplayDownSamplingRate, 3, 0, 1, 1)
        self.CenterPlot = QtGui.QCheckBox(self.groupBox_2)
        self.CenterPlot.setChecked(True)
        self.CenterPlot.setObjectName(_fromUtf8("CenterPlot"))
        self.gridLayout_7.addWidget(self.CenterPlot, 0, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.groupBox_2)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_7.addWidget(self.label_6, 1, 0, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralWidget)
        self.groupBox.setGeometry(QtCore.QRect(800, 340, 199, 311))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.FromRawData = QtGui.QCheckBox(self.groupBox)
        self.FromRawData.setObjectName(_fromUtf8("FromRawData"))
        self.gridLayout_6.addWidget(self.FromRawData, 2, 0, 1, 1)
        self.EventsFound = QtGui.QLabel(self.groupBox)
        self.EventsFound.setText(_fromUtf8(""))
        self.EventsFound.setObjectName(_fromUtf8("EventsFound"))
        self.gridLayout_6.addWidget(self.EventsFound, 7, 0, 1, 1)
        self.EventCoeff = QtGui.QDoubleSpinBox(self.groupBox)
        self.EventCoeff.setMaximum(100.0)
        self.EventCoeff.setSingleStep(0.5)
        self.EventCoeff.setProperty("value", 5.0)
        self.EventCoeff.setObjectName(_fromUtf8("EventCoeff"))
        self.gridLayout_6.addWidget(self.EventCoeff, 4, 0, 1, 1)
        self.UpwardEventsAllowed = QtGui.QCheckBox(self.groupBox)
        self.UpwardEventsAllowed.setEnabled(False)
        self.UpwardEventsAllowed.setObjectName(_fromUtf8("UpwardEventsAllowed"))
        self.gridLayout_6.addWidget(self.UpwardEventsAllowed, 1, 0, 1, 1)
        self.EventDetectionSwitch = QtGui.QCheckBox(self.groupBox)
        self.EventDetectionSwitch.setObjectName(_fromUtf8("EventDetectionSwitch"))
        self.gridLayout_6.addWidget(self.EventDetectionSwitch, 0, 0, 1, 2)
        self.EventsFoundUP = QtGui.QLabel(self.groupBox)
        self.EventsFoundUP.setText(_fromUtf8(""))
        self.EventsFoundUP.setObjectName(_fromUtf8("EventsFoundUP"))
        self.gridLayout_6.addWidget(self.EventsFoundUP, 8, 0, 1, 1)
        self.EventThreshold = QtGui.QLabel(self.groupBox)
        self.EventThreshold.setText(_fromUtf8(""))
        self.EventThreshold.setObjectName(_fromUtf8("EventThreshold"))
        self.gridLayout_6.addWidget(self.EventThreshold, 6, 0, 1, 1)
        self.MinDwellTimeED = QtGui.QDoubleSpinBox(self.groupBox)
        self.MinDwellTimeED.setMaximum(100000.0)
        self.MinDwellTimeED.setSingleStep(100.0)
        self.MinDwellTimeED.setProperty("value", 500.0)
        self.MinDwellTimeED.setObjectName(_fromUtf8("MinDwellTimeED"))
        self.gridLayout_6.addWidget(self.MinDwellTimeED, 5, 0, 1, 1)
        self.groupBox_3 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_3.setGeometry(QtCore.QRect(580, 340, 201, 171))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.currentIDC = QtGui.QLabel(self.groupBox_3)
        self.currentIDC.setObjectName(_fromUtf8("currentIDC"))
        self.gridLayout_5.addWidget(self.currentIDC, 2, 0, 1, 1)
        self.currentRMS = QtGui.QLabel(self.groupBox_3)
        self.currentRMS.setObjectName(_fromUtf8("currentRMS"))
        self.gridLayout_5.addWidget(self.currentRMS, 1, 0, 1, 1)
        self.currentRMSRaw = QtGui.QLabel(self.groupBox_3)
        self.currentRMSRaw.setObjectName(_fromUtf8("currentRMSRaw"))
        self.gridLayout_5.addWidget(self.currentRMSRaw, 0, 0, 1, 1)
        self.CurrentCond = QtGui.QLabel(self.groupBox_3)
        self.CurrentCond.setObjectName(_fromUtf8("CurrentCond"))
        self.gridLayout_5.addWidget(self.CurrentCond, 3, 0, 1, 1)
        self.groupBox_8 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_8.setGeometry(QtCore.QRect(430, 530, 351, 121))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayoutWidget_4 = QtGui.QWidget(self.groupBox_8)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 22, 321, 91))
        self.gridLayoutWidget_4.setObjectName(_fromUtf8("gridLayoutWidget_4"))
        self.gridLayout_12 = QtGui.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.ZappingChooser = QtGui.QComboBox(self.gridLayoutWidget_4)
        self.ZappingChooser.setObjectName(_fromUtf8("ZappingChooser"))
        self.ZappingChooser.addItem(_fromUtf8(""))
        self.ZappingChooser.addItem(_fromUtf8(""))
        self.gridLayout_12.addWidget(self.ZappingChooser, 2, 1, 1, 2)
        self.ZappingLimit = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.ZappingLimit.setProperty("value", 2.0)
        self.ZappingLimit.setObjectName(_fromUtf8("ZappingLimit"))
        self.gridLayout_12.addWidget(self.ZappingLimit, 2, 3, 1, 1)
        self.ZapButton = QtGui.QPushButton(self.gridLayoutWidget_4)
        self.ZapButton.setObjectName(_fromUtf8("ZapButton"))
        self.gridLayout_12.addWidget(self.ZapButton, 1, 0, 1, 4)
        self.ZapVoltage = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.ZapVoltage.setMinimum(-1.0)
        self.ZapVoltage.setMaximum(1.0)
        self.ZapVoltage.setProperty("value", -0.3)
        self.ZapVoltage.setObjectName(_fromUtf8("ZapVoltage"))
        self.gridLayout_12.addWidget(self.ZapVoltage, 0, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_12.addWidget(self.label_7, 0, 2, 1, 1)
        self.ZapTime = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.ZapTime.setSingleStep(0.5)
        self.ZapTime.setProperty("value", 0.5)
        self.ZapTime.setObjectName(_fromUtf8("ZapTime"))
        self.gridLayout_12.addWidget(self.ZapTime, 0, 3, 1, 1)
        self.label_2 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_12.addWidget(self.label_2, 0, 0, 1, 1)
        self.AutoZapOn = QtGui.QCheckBox(self.gridLayoutWidget_4)
        self.AutoZapOn.setObjectName(_fromUtf8("AutoZapOn"))
        self.gridLayout_12.addWidget(self.AutoZapOn, 2, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.gridLayoutWidget_4)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_12.addWidget(self.label_8, 3, 0, 1, 1)
        self.ZappingFrequency = QtGui.QDoubleSpinBox(self.gridLayoutWidget_4)
        self.ZappingFrequency.setProperty("value", 2.0)
        self.ZappingFrequency.setObjectName(_fromUtf8("ZappingFrequency"))
        self.gridLayout_12.addWidget(self.ZappingFrequency, 3, 1, 1, 3)
        self.groupBox_9 = QtGui.QGroupBox(self.centralWidget)
        self.groupBox_9.setGeometry(QtCore.QRect(260, 0, 761, 331))
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.CurrentPlot = PlotWidget(self.groupBox_9)
        self.CurrentPlot.setGeometry(QtCore.QRect(20, 20, 721, 301))
        self.CurrentPlot.setObjectName(_fromUtf8("CurrentPlot"))
        mainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(mainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 1023, 21))
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuChimera_Software = QtGui.QMenu(self.menuBar)
        self.menuChimera_Software.setObjectName(_fromUtf8("menuChimera_Software"))
        self.menuBlabla = QtGui.QMenu(self.menuBar)
        self.menuBlabla.setObjectName(_fromUtf8("menuBlabla"))
        mainWindow.setMenuBar(self.menuBar)
        self.statusBar = QtGui.QStatusBar(mainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        mainWindow.setStatusBar(self.statusBar)
        self.SaveDataFromDisplay = QtGui.QAction(mainWindow)
        self.SaveDataFromDisplay.setCheckable(True)
        self.SaveDataFromDisplay.setObjectName(_fromUtf8("SaveDataFromDisplay"))
        self.SaveDataVoltage = QtGui.QAction(mainWindow)
        self.SaveDataVoltage.setCheckable(True)
        self.SaveDataVoltage.setObjectName(_fromUtf8("SaveDataVoltage"))
        self.USBTransfer = QtGui.QAction(mainWindow)
        self.USBTransfer.setCheckable(True)
        self.USBTransfer.setChecked(True)
        self.USBTransfer.setObjectName(_fromUtf8("USBTransfer"))
        self.ResetBufferButton = QtGui.QAction(mainWindow)
        self.ResetBufferButton.setObjectName(_fromUtf8("ResetBufferButton"))
        self.menuChimera_Software.addAction(self.USBTransfer)
        self.menuChimera_Software.addAction(self.ResetBufferButton)
        self.menuBlabla.addAction(self.SaveDataFromDisplay)
        self.menuBlabla.addAction(self.SaveDataVoltage)
        self.menuBar.addAction(self.menuChimera_Software.menuAction())
        self.menuBar.addAction(self.menuBlabla.menuAction())

        self.retranslateUi(mainWindow)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(mainWindow)

    def retranslateUi(self, mainWindow):
        mainWindow.setWindowTitle(_translate("mainWindow", "Chimera Software", None))
        self.groupBox_5.setTitle(_translate("mainWindow", "Action", None))
        self.label.setText(_translate("mainWindow", "Bias:", None))
        self.VoltageChooser.setSuffix(_translate("mainWindow", " Volts", None))
        self.ZeroVolt.setText(_translate("mainWindow", "0 V", None))
        self.p100.setText(_translate("mainWindow", "+100 mV", None))
        self.p10.setText(_translate("mainWindow", "+10 mV", None))
        self.n10.setText(_translate("mainWindow", "-10 mV", None))
        self.n100.setText(_translate("mainWindow", "-100 mV", None))
        self.p50.setText(_translate("mainWindow", "+50 mV", None))
        self.n50.setText(_translate("mainWindow", "-50 mV", None))
        self.negateBias.setText(_translate("mainWindow", "+ / -", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("mainWindow", "Field", None))
        self.mv200.setText(_translate("mainWindow", "200 mV", None))
        self.mv500.setText(_translate("mainWindow", "500 mV", None))
        self.mv400.setText(_translate("mainWindow", "400 mV", None))
        self.mv100.setText(_translate("mainWindow", "100 mV", None))
        self.mv300.setText(_translate("mainWindow", "300 mV", None))
        self.mv200n.setText(_translate("mainWindow", "-200 mV", None))
        self.mv100n.setText(_translate("mainWindow", "-100 mV", None))
        self.mv300n.setText(_translate("mainWindow", "-300 mV", None))
        self.mv400n.setText(_translate("mainWindow", "-400 mV", None))
        self.mv500n.setText(_translate("mainWindow", "-500 mV", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("mainWindow", "Buttons", None))
        self.MakeIV.setText(_translate("mainWindow", "Make IV", None))
        self.label_3.setText(_translate("mainWindow", "Step Size", None))
        self.label_4.setText(_translate("mainWindow", "Bounds", None))
        self.label_5.setText(_translate("mainWindow", "Dwell Time", None))
        self.IVBounds.setSuffix(_translate("mainWindow", " Volts", None))
        self.IVStep.setSuffix(_translate("mainWindow", " Volts", None))
        self.IVDwell.setSuffix(_translate("mainWindow", " Seconds", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("mainWindow", "IV Settings", None))
        self.groupBox_6.setTitle(_translate("mainWindow", "Technical Details", None))
        self.ZeroVoltage.setText(_translate("mainWindow", "Zero Voltage", None))
        self.zerovoltagevlaue.setSuffix(_translate("mainWindow", " Volts", None))
        self.ZeroCurrent.setText(_translate("mainWindow", "Zero Current", None))
        self.ZeroCurrentValue.setText(_translate("mainWindow", "TextLabel", None))
        self.groupBox_7.setTitle(_translate("mainWindow", "Input/Output", None))
        self.InputChooser.setItemText(0, _translate("mainWindow", "Filtered", None))
        self.InputChooser.setItemText(1, _translate("mainWindow", "Unfiltered", None))
        self.InputChooser.setItemText(2, _translate("mainWindow", "VIN1", None))
        self.InputChooser.setItemText(3, _translate("mainWindow", "AUX J14", None))
        self.Reconnect.setText(_translate("mainWindow", "Connect To Chimera", None))
        self.ExperimentName.setToolTip(_translate("mainWindow", "<html><head/><body><p>Change The Experiment Name...</p></body></html>", None))
        self.ExperimentName.setText(_translate("mainWindow", "Exp Name", None))
        self.SaveData.setText(_translate("mainWindow", "Saving On", None))
        self.WrittenBlocks.setText(_translate("mainWindow", "Written Blocks", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_4), _translate("mainWindow", "Saving", None))
        self.SetDataFolder.setText(_translate("mainWindow", "Set Data Folder", None))
        self.tabWidget_2.setTabText(self.tabWidget_2.indexOf(self.tab_5), _translate("mainWindow", "Set Saving Folder", None))
        self.groupBox_2.setTitle(_translate("mainWindow", "Display Settings", None))
        self.LowPassValue.setSuffix(_translate("mainWindow", " kHz", None))
        self.LowPass.setText(_translate("mainWindow", "Low Pass", None))
        self.CenterPlot.setText(_translate("mainWindow", "Center Plot", None))
        self.label_6.setText(_translate("mainWindow", "Display Downsamplerate", None))
        self.groupBox.setTitle(_translate("mainWindow", "Event Detection", None))
        self.FromRawData.setText(_translate("mainWindow", "Use raw data for detection", None))
        self.EventCoeff.setSuffix(_translate("mainWindow", " x std of baseline", None))
        self.UpwardEventsAllowed.setText(_translate("mainWindow", "Allow Upward Events", None))
        self.EventDetectionSwitch.setText(_translate("mainWindow", "Turn On", None))
        self.MinDwellTimeED.setSuffix(_translate("mainWindow", " us min dwell time", None))
        self.groupBox_3.setTitle(_translate("mainWindow", "Infos", None))
        self.currentIDC.setText(_translate("mainWindow", "TextLabel", None))
        self.currentRMS.setText(_translate("mainWindow", "TextLabel", None))
        self.currentRMSRaw.setText(_translate("mainWindow", "TextLabel", None))
        self.CurrentCond.setText(_translate("mainWindow", "TextLabel", None))
        self.groupBox_8.setTitle(_translate("mainWindow", "Auto Zap", None))
        self.ZappingChooser.setItemText(0, _translate("mainWindow", "if Conductance <", None))
        self.ZappingChooser.setItemText(1, _translate("mainWindow", "if Current < ", None))
        self.ZappingLimit.setSuffix(_translate("mainWindow", " nS", None))
        self.ZapButton.setText(_translate("mainWindow", "Zap", None))
        self.ZapVoltage.setSuffix(_translate("mainWindow", " Volts", None))
        self.label_7.setText(_translate("mainWindow", "for", None))
        self.ZapTime.setSuffix(_translate("mainWindow", " seconds", None))
        self.label_2.setText(_translate("mainWindow", "Zap with", None))
        self.AutoZapOn.setText(_translate("mainWindow", "Auto Zap", None))
        self.label_8.setText(_translate("mainWindow", "Zap every", None))
        self.ZappingFrequency.setSuffix(_translate("mainWindow", " seconds", None))
        self.groupBox_9.setTitle(_translate("mainWindow", "Live Trace", None))
        self.menuChimera_Software.setTitle(_translate("mainWindow", "Chimera Software", None))
        self.menuBlabla.setTitle(_translate("mainWindow", "Saving Options", None))
        self.SaveDataFromDisplay.setText(_translate("mainWindow", "Save the displayed trace", None))
        self.SaveDataVoltage.setText(_translate("mainWindow", "Save the bias values", None))
        self.USBTransfer.setText(_translate("mainWindow", "USB Transfer", None))
        self.ResetBufferButton.setText(_translate("mainWindow", "Reset Buffer", None))

from pyqtgraph import PlotWidget
